WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720


GAME_WIDTH = 320
GAME_HEIGHT = 180

FPS = 60
TILESIZE = 16

BAR_HEIGHT = 20
HEALTH_BAR_WIDTH = 200
ENERGY_BAR_WIDTH = 140
ITEM_BOX_SIZE = 80
UI_FONT = './assets/graphics/font/joystix.ttf' 
UI_FONT_SIZE = 18

WATER_COLOR = '#71ddee'
UI_BG_COLOR = '#222222'
UI_BORDER_COLOR = '#111111'
TEXT_COLOR = '#EEEEEE'

HEALTH_COLOR = 'red'
ENERGY_COLOR = 'cyan' 
UI_BORDER_COLOR_ACTIVE = 'gold'


ENEMIES = ['skeleton', 'vampire', 'ghost']

SHIFT_X = 16 * 16
SHIFT_Y = 16 * 15

SHIFT_X_PLAYER = None
SHIFT_Y_PLAYER = None 

SHIFT_X_ENEMIES = 32 
SHIFT_Y_ENEMIES = 100