[project]
name = "pathfinder"
version = "0.1.0"
authors = [
  { name="Gabriel Cássio", email="gabriel.cgc.contato@gmail.com" }
]
description = "Ainda em desenvolvimento"
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
